### ISSUE TITLE
There seems to be something wrong with "uncountable".

### ISSUE THREAD

**Issue by davideder** [kbatsuren/MorphyNet#4]
If you look for records with uncountable in eng.inflectional.v1.tsv, you will quickly see the problem.

Here are the first 20:

unsleep	uncountable	N;PL	-
unsleep	uncountable	N;PL	-
farspeak	uncountable	N;PL	-
grill	uncountable	N;PL	-
kybosh	uncountable	N;PL	-
keratoleukoma	uncountable	N;PL	-
husk	uncountable	N;PL	-
courage	uncountable	N;PL	-
loo	uncountable	N;PL	-
amaze	uncountable	N;PL	-
baksheesh	uncountable	N;PL	-
dead	uncountable	N;PL	-
snet	uncountable	N;PL	-
bebop	uncountable	N;PL	-
rue	uncountable	N;PL	-
dayee	uncountable	N;PL	-
accuse	uncountable	N;PL	-
inwork	uncountable	N;PL	-
eid	uncountable	N;PL	-
alt	uncountable	N;PL	-

**Comment by kbatsuren** [comment]
Thank you so much for pointing it out. 

The solution is simply to replace "uncountable" with the first column text. @Tselmuunkoko, could you fix it and send the pull request?

**Comment by davideder** [comment]
Seems to be the same issue with "countable" too.

Thanks,

David.

On 2022-07-18 4:33 am, Khuyagbaatar Batsuren wrote:

> Thank you so much for pointing it out.
> 
> The solution is simply to replace "uncountable" with the first column 
> text. @Tselmuunkoko [1], could you fix it and send the pull request?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/Tselmuunkoko
[2] 
https://github.com/kbatsuren/MorphyNet/issues/4#issuecomment-1187034384
[3]

**Comment by kbatsuren** [comment]
@davideder, For the issue of "countable," I need to fix it myself from the Wiktionary extraction process. So could you create another issue? I will fix it in August.
