### ISSUE TITLE
missing morpheme segmentations Italian

### ISSUE THREAD

**Issue by francescocabiddu** [kbatsuren/MorphyNet#7]
Hi, for some words in the Italian inflectional list, the morpheme segmentation is indicated as "-". Is this missing or does it mean that the word can be segmented as a whole-word morpheme?

**Comment by kbatsuren** [comment]
Thank you very much for using the resource! 

As far as I remember it, '-' is only being used when the source lemma and target inflection are exactly the same. 

I am closing this issue. If you find any other issue with '-' instances, please reopen a new issue.
